### ISSUE TITLE
Thermostat_state not set when different from next automatic program state

### ISSUE THREAD

**Issue by JohnvandeVrugt** [costastf/toonapilib#24]
Hi Costas,

I think I have discovered another one. Testing with v3.0.10.

My Toon is running with the thermostat program active.
In other words Toon determines the state of the thermostat according to the planning/time of day.

When the program is set to the active state according to the planning, toonapilib does not change the state anymore. At least it does for 'sleep'.

The TOON app allows changing to any state. So when I change the state by means of the app, the toonapilib can change programs again. Until sleep is activated. In that case all new changes are discarded.

Hope you have a quick look.
Meanwhile I pythonized my plugin a little bit more ;)

Thanks in advance!
John

**Comment by costastf** [comment]
Hi John, looked into it and there is a race condition on the api submission that I cannot identify. This is definitely something that is a bug with the api. I will have a look into how the app is working and try to figure it out that way, because from experience, communicating with the Toon developers on clarifying their api does not bear too much fruit.

**Comment by costastf** [comment]
On the other hand it wouldn't hurt if you contact them and ask for clarification of this feature. The api end point that sets temperature and states is the same with the same payload, so in order to apply something all values need to be delivered with the appropriate ones masked. This is not documented at all and in the active program state I was not able to make it work with some trivial experimentation. Maybe it is time they updated their documentation.

**Comment by costastf** [comment]
Had a look at your code also, it progresses quite fine! If you like a code review, let me know.

**Comment by JohnvandeVrugt** [comment]
Hi Costas, 

Having some carnaval issues right now ;)
Will get back to you

**Comment by costastf** [comment]
Enjoy! :)

**Comment by costastf** [comment]
Fix is in v.3.0.11. Thanks @JohnvandeVrugt for the PR and everyone for testing it, greatly appreciated!
