### ISSUE TITLE
Handle statuscode 429

### ISSUE THREAD

**Issue by frenck** [costastf/toonapilib#33]
When the Toon API limit is reached / hit, the API throws an HTTP 429 status code.

This should be handled properly by the library (e.g., by implementing a proper back off).

**Comment by costastf** [comment]
i think that the default caching covers this so there is no need to implement anything more towards this issue.

**Comment by frenck** [comment]
? That is not an answer or solution.
These can be triggered by all kinds of things, e.g., temporary less capacity, a ton of temperature changes send in the past x minutes.

Caching is not a magical keyword in this case.

**Comment by costastf** [comment]
I realize that and I am not super happy with the way things are handled but
I am also very short on extra personal time and since things are working I
would rather spend my very limited time into solving things that actually
create problems. I would be more than happy to accept MRs to fix this the
proper way.
