### ISSUE TITLE
integration in Home Assistant is not working

### ISSUE THREAD

**Issue by worker72** [costastf/toonapilib#51]
Toonapilib is integrated into Home Assistant (HA). Unfortunately, after about 30 minutes the information flow from the "integration" in HA stops. 

My HA log can be found here:
[home-assistant.log](https://github.com/costastf/toonapilib/files/4616229/home-assistant.log)

What is also very unfortunate
* the Toonapilib that is integrated into HA is version 3.2.4
* I have very limited skills in python, github etc. 

I would *really* appreciate feedback on the log: could this be solved with going to the newest version of Toonapilib? If I know that, maybe I can pursue someone at HA to integrate the newest version

**Comment by frenck** [comment]
I am actually working on that and currently testing an upgraded integration for Home Assistant.

**Comment by costastf** [comment]
@worker72 i am sorry to say that it will not be fixed by going to the latest version. Just to give a bit of context on this, while this library (actually it's predecessor toonlib) was created with HA in mind i did not keep up with the amazing development the guys have been doing on HA (actually until last week, I was running v.0.57 of HA myself) so when I got pinged a while back from Quby that for long running libraries they have implemented a simple long lived token based authentication I removed the oauth implementation and just implemented that. That of course would break all kinds of stuff and other integrations than Eneco which I was not aware of and since HA implements an oauth authentication itself it would not work. That was a bit about the context and the difference of the latest version (nothing functional, apart from the authentication part).
@frenck is there anything that I can do to help with this? Can I refactor to some specification? The way I see things is that if we don't want to have the long lived token implementation on HA since it is not compatible with all providers, and since HA implements the initial handshake, the library should expect and initial set of valid credentials but it should be able to detect the expiry and refresh them, which means that I would need to re implement the updating of tokens which I would not mind doing.
If i can help with meeting your efforts half way please let me know @frenck .

**Comment by darkrain-nl** [comment]
Hi guys/girls,

Please keep in mind this library is also used on other projects, like Domoticz, which needs the long token. Hopefully that will not break when this is fixed.

**Comment by costastf** [comment]
@darkrain-nl nah, don't worry, that functionality will stay of course.

**Comment by darkrain-nl** [comment]
@costastf thanks, was just making sure ;)

**Comment by costastf** [comment]
Home assistant has implemented a new underlying mechanism for toon that does not depend on this library anymore, so closing this.
